### ISSUE TITLE
E: Package 'couchdb' has no installation candidate

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/couchdb_ynh#14]
### Describe the bug

E: Package 'couchdb' has no installation candidate

### Context

- Hardware: *odroid hc1 **ARMHF** >armbian 21.x>lxd>debian buster (linux 4.14)*
- YunoHost version: 4.2.7
- I have access to my server: *through the webadmin | *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable

### Steps to reproduce

install couchdb app

### Expected behavior

couchdb app insalled

### Logs
https://paste.yunohost.org/raw/nohaderuza

**Comment by eauchat** [comment]
I'm a bit lost with the many changes that occurred in the package. Also the change of repository where to get couchdb from. I don't understand all of it anymore.  
I have no idea if those errors you get could come from that, or from somewhere else as I'm confused with the error logs.  
Maybe @ericgaspar would be more knowledgeable to help you out.

**Comment by yalh76** [comment]
There is no armhf version available, look at https://apache.jfrog.io/ui/native/couchdb-deb/dists/bullseye/main/
