### ISSUE TITLE
“Port 5984 is not reachable from outside.”

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/couchdb_ynh#18]
### Describe the bug

Even though all ports are enabled on my server, I get the following error:

<img width="1120" alt="Screenshot 2022-02-21 at 6 42 03 PM" src="https://user-images.githubusercontent.com/42862428/155004539-f7010590-d67e-4be8-9d5d-b6e8853a7b26.png">

<br>

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

<br>

### Steps to reproduce

1. `sudo yunohost app install couchdb`
1. Running the YunoHost diagnosis
1. Getting `Port 5984 is not reachable from outside.`

<br>

### Expected behavior

Port 5984 should be working and exposed

<br>

### Logs

[Log](https://paste.yunohost.org/raw/ikequzavap)

**Comment by tituspijean** [comment]
Mmmh, I am not sure this port should be publicly accessible.

Culprit line: https://github.com/YunoHost-Apps/couchdb_ynh/blob/7383f47de49254813e3c03b4a11d870bf24b94c5/scripts/install#L129

What do you think, @eauchat?

**Comment by eauchat** [comment]
Mmmh well indeed, it's true that there shouldn't be any necessity to have the port accessible from the outside, since nginx is actually directing outside's traffic for the app to port 5984.
I think the code has already been corrected by a PR of @ericgaspar.

**Comment by yalh76** [comment]
Port 5984is not available from outside, it's proxyed by nginx
