### ISSUE TITLE
CouchDb is unreachable from CLI

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/couchdb_ynh#19]
### Describe the bug

There appears to be a SSL error while reaching my CouchDB instance, at [`https://db.tommi.space`](https://db.tommi.space).

<br>

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

<br>

### Steps to reproduce

1. From a remote client, run `curl -X GET https://db.tommi.space/_all_dbs`
1. the resulting error is `curl: (35) error:1400442E:SSL routines:CONNECT_CR_SRVR_HELLO:tlsv1 alert protocol version`
2. Same goes for any `PUT` request

<br>

### Expected behavior

All of my databases should be returned.

<br>

### Logs

I effectively installed a Let’s Encrypt certificate for the domain, the log is [here](https://paste.yunohost.org/raw/sedasalega)

**Comment by eauchat** [comment]
Couldn't reproduce your issue. Do you still have the problem?

**Comment by xplosionmind** [comment]
thanks for getting back, @eauchat. Yes, I am still experiencing some trouble

**Comment by eauchat** [comment]
I don't know how to help you. I'm wondering if the issue is related to couchdb, this package, or yunohost directly Maybe if you have an idea of what more context or related logs you can provide, someone here or on the [forum](https://forum.yunohost.org) may have some good idea.

**Comment by yalh76** [comment]
The https parameters comes from YunoHost and have been updated when migrating from buster to bullseye

You should retest
